[package]
name = "cli_google_search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
html2text = "0.9.1"
ureq = "2.9.1"
url = "2.5.0"
